---

- name: set package lists based on RHEL version
  ansible.builtin.set_fact:
    growpart_packages: "{{ ['cloud-utils-growpart'] + (['gdisk'] if ansible_distribution_major_version|int < 10 else []) }}"
- name: ensure growpart packages are installed
  ansible.builtin.package:
    name: "{{ growpart_packages }}"

- name: create growpart cloud-init script to grow partition on boot
  ansible.builtin.template:
    src: grow_part.sh.j2
    dest: /usr/local/bin/grow_part.sh
    mode: u=rwx,g=rx,o=rx

- name: copy growpart service
  ansible.builtin.copy:
    src: growpart.service
    dest: /etc/systemd/system/growpart.service
    mode: '0755'

- name: reload service
  ansible.builtin.systemd:
    name: growpart
    daemon_reload: true
    enabled: true
    state: stopped
