---

- name: epel
  block:
    - name: import epel gpg key
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

    - name: ensure epel is installed
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      register: install_epel
      until: '"error" not in install_epel'
      retries: 5
      delay: 10
  when: ansible_distribution == 'CentOS'

# rhevm-guest-agent-common package is not yet available for RHEL 8
- name: ensure ovirt guest agent package is installed
  ansible.builtin.package:
    name: "{{ ovirt_guest_agent_package_name[ansible_distribution] }}"
  register: ovirt_package_installation
  when: ansible_distribution_major_version|int < 8

- name: ensure qemu guest agent package is installed
  ansible.builtin.package:
    name: "{{ qemu_guest_agent_package_name }}"
  when: ansible_distribution_major_version|int >= 8
  register: qemu_package_installation
  ignore_errors: true

- name: enable ovirt guest agent
  block:
    - name: ensure ovirt guest agent is enabled (RHEL < 8)
      ansible.builtin.service:
        name: "{{ ovirt_guest_agent_service_name }}"
        enabled: true
      when: ansible_distribution_major_version|int < 8

    - name: ensure qemu guest agent is enabled (RHEL >= 8)
      ansible.builtin.service:
        name: "{{ qemu_guest_agent_service_name }}"
        enabled: true
      when: ansible_distribution_major_version|int >= 8
  when: qemu_package_installation is succeeded
