---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Rocky Linux 8
  - name: instance-rocky8
    image: ${MOLECULE_DISTRO:-quay.io/rockylinux/rockylinux:8}
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    published_ports:
      - "0.0.0.0:2222:22/tcp"
    networks:
      - name: molecule
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined

  # Rocky Linux 9
  - name: instance-rocky9
    image: ${MOLECULE_DISTRO:-quay.io/rockylinux/rockylinux:9}
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    published_ports:
      - "0.0.0.0:2223:22/tcp"
    networks:
      - name: molecule
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined

  # Rocky Linux 10 (NEW!)
  - name: instance-rocky10
    image: ${MOLECULE_DISTRO:-quay.io/rockylinux/rockylinux:10}
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    published_ports:
      - "0.0.0.0:2224:22/tcp"
    networks:
      - name: molecule
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined

  # AlmaLinux 8
  - name: instance-alma8
    image: ${MOLECULE_DISTRO:-quay.io/almalinuxorg/almalinux:8}
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    published_ports:
      - "0.0.0.0:2225:22/tcp"
    networks:
      - name: molecule
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined

  # AlmaLinux 9
  - name: instance-alma9
    image: ${MOLECULE_DISTRO:-quay.io/almalinuxorg/almalinux:9}
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    published_ports:
      - "0.0.0.0:2226:22/tcp"
    networks:
      - name: molecule
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined

  # AlmaLinux 10 (NEW!)
  - name: instance-alma10
    image: ${MOLECULE_DISTRO:-quay.io/almalinuxorg/almalinux:10}
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    published_ports:
      - "0.0.0.0:2227:22/tcp"
    networks:
      - name: molecule
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
verifier:
  name: ansible
