---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-quay.io/rockylinux/rockylinux:9}
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    environment:
      container: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks
      stdout_callback: yaml
      bin_ansible_callbacks: true
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      instance:
        ansible_user: root
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/tests/roles
    ANSIBLE_CONFIG: ${MOLECULE_SCENARIO_DIRECTORY}/ansible.cfg
  playbooks:
    prepare: ${MOLECULE_SCENARIO_DIRECTORY}/prepare.yml
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml
    verify: ${MOLECULE_SCENARIO_DIRECTORY}/verify.yml
  ansible_args:
    - --diff
    - -v

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
