---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/rockylinux/rockylinux:9
    privileged: true
    command: /usr/sbin/init
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
