---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/rockylinux/rockylinux:9
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    pre_build_image: false
    dockerfile: Dockerfile.j2

provisioner:
  name: ansible

verifier:
  name: ansible
