---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/rockylinux/rockylinux:9-ubi-init
    privileged: true
    command: /usr/lib/systemd/systemd
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
