---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    # Enhanced wait strategy for container readiness
    - name: Wait for systemd to start
      ansible.builtin.wait_for:
        port: 22
        host: "{{ ansible_host | default(inventory_hostname) }}"
        timeout: 60
        delay: 5
      delegate_to: localhost
      retries: 3
      delay: 10

    - name: Wait for container SSH service
      ansible.builtin.wait_for_connection:
        timeout: 120
        sleep: 5
        delay: 10
      retries: 5
      delay: 15

    # Alternative connection method if direct fails
    - name: Test basic connectivity with ping
      ansible.builtin.ping:
      register: ping_result
      retries: 3
      delay: 10
      until: ping_result is succeeded

    # Ensure SSH service is running
    - name: Start SSH service if needed
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: true
      failed_when: false

    # Final connectivity verification
    - name: Verify container is ready for testing
      ansible.builtin.command: echo "Container ready"
      changed_when: false
