---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    # Wait for SSH port to be available
    - name: Wait for SSH port
      ansible.builtin.wait_for:
        port: 22
        host: "{{ ansible_host | default(inventory_hostname) }}"
        timeout: 60
        delay: 5
      delegate_to: localhost
      retries: 3
      delay: 10

    # Simple connection test with retries
    - name: Wait for SSH connection
      ansible.builtin.wait_for_connection:
        timeout: 120
        sleep: 10
        delay: 15
      retries: 5
      delay: 15

    # Test basic connectivity
    - name: Test basic connectivity
      ansible.builtin.ping:
      retries: 3
      delay: 5

    - name: Container ready
      ansible.builtin.debug:
        msg: "Container is ready for testing"
