---
name: Deploy to Ansible Galaxy

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger
    inputs:
      tag_name:
        description: 'Tag name (e.g., v1.0.0)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ansible-core
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Get the version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.inputs.tag_name || 'main' }}" >> $GITHUB_OUTPUT
          fi

      - name: Verify role metadata
        run: |
          echo "Checking role metadata..."
          ansible-galaxy role info . || true

      - name: Import role to Galaxy
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        run: |
          # For tag-based releases, we don't specify branch
          # This ensures Galaxy uses the tag reference
          ansible-galaxy role import \
            --api-key="${ANSIBLE_GALAXY_API_KEY}" \
            oatakan rhel_template_build

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## What's Changed
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.get_version.outputs.PREVIOUS_TAG }}...${{ steps.get_version.outputs.VERSION }}
            
            ## Installation
            
            ```bash
            ansible-galaxy install oatakan.rhel_template_build,v${{ steps.get_version.outputs.VERSION }}
            ```