name: VM Integration Tests

on:
  workflow_dispatch:
    inputs:
      test_os:
        description: 'OS to test'
        required: true
        default: 'rocky9'
        type: choice
        options:
          - rocky8
          - rocky9
          - alma8
          - alma9
          - centos7

  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  vm-test:
    runs-on: [self-hosted, vm-capable]  # Requires self-hosted runner with virtualization
    strategy:
      fail-fast: false
      matrix:
        os:
          - ${{ github.event.inputs.test_os || 'rocky9' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-plugins[vagrant]

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install community.general ansible.posix

      - name: Install test role
        run: |
          cat <<'EOF' > requirements.yml
          - src: https://github.com/${{ github.repository }}.git
            scm: git
            version: ${{ github.event.pull_request.head.sha || github.sha }}
            name: oatakan.rhel_template_build
          EOF
          ansible-galaxy role install -r requirements.yml -p ${{ github.workspace }}/tests/roles
          rm requirements.yml

      - name: Run Molecule vagrant tests
        run: |
          cd molecule/vagrant
          molecule test
        env:
          ANSIBLE_ROLES_PATH: ${{ github.workspace }}/tests/roles
          MOLECULE_VAGRANT_BOX: generic/${{ matrix.os }}

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: molecule-logs-${{ matrix.os }}
          path: |
            molecule/vagrant/.molecule/
            ~/.cache/molecule/
